### ISSUE TITLE
Is this a typo?

### ISSUE THREAD

**Issue by zdplayground** [desihub/LSS#20]
https://github.com/desihub/LSS/blob/29a3cafe842f74ce7780d69aa1423e936475fe6b/py/LSS/SV3/fatools.py#L253

Should be "exit"?

**Comment by ashleyjross** [comment]
Yes; thanks! It will be fixed next time I commit. @araichoor you might want to fix this where it was copied from (create_mtl I believe, if you haven't already!)

**Comment by araichoor** [comment]
oh right, thanks.
as this is in a case that never happened (some sanity check in the case we apply the proper motion correction, which we do not do), I missed that.
