### ISSUE TITLE
LSS code should be licensed

### ISSUE THREAD

**Issue by weaverba137** [desihub/LSS#3]
Please consider adding a license file to this code.  The DESI data team strongly recommends the BSD-3-clause license.  See the LICENSE.rst file in the desitemplate package for an example.

**Comment by weaverba137** [comment]
@ashleyjross, you get the assignment since you seem to be actively working on this package.

**Comment by ashleyjross** [comment]
Ok, I think I just did that. Have a look at the PR.

**Comment by weaverba137** [comment]
Fixed by #6.
