### ISSUE TITLE
Bug found in LSS.bitweights. Not importing correctly

### ISSUE THREAD

**Issue by aureliocarnero** [desihub/LSS#32]
I think there is an error in the library bitweights.py after merging with ScriptingAltMTLs

I cannot import it because there is an incomplete import at the start.

Now it reads:
try:
    from fiberassign.targets import (Targets, TargetsAvailable, TargetTree,
                                 LocationsAvailable, load_target_table)
except:
    from fiberassign.targets import (Targets, TargetsAvailable,

Inside the except, the line is broken, looking at a previous version, I think it should be:

try:
    from fiberassign.targets import (Targets, TargetsAvailable, TargetTree,
                                 LocationsAvailable, load_target_table)
except:
    from fiberassign.targets import (Targets, TargetsAvailable,
                                 LocationsAvailable, load_target_table)

**Comment by ashleyjross** [comment]
Yes, please go ahead and make the suggested change. I think what we should do eventually is put these imports somewhere further down in the code and make them depend on the version of fiberassign being used, but this fix is fine for now.
