### ISSUE TITLE
Add FIRST_NIGHT and LAST_NIGHT to qso catalog

### ISSUE THREAD

**Issue by julienguy** [desihub/LSS#66]
- Looking at the code [LSS/py/LSS/qso_cat_utils.py] after Alma's post, it would be great to add columns FIRST_NIGHT , LAST_NIGHT , than can be computed using the NIGHT column grabbed from EXP_FIBERMAP of the coadd files. 
- We could also add FIRST_MJD , MEAN_MJD, LAST_MJD from the same table.

**Comment by ashleyjross** [comment]
I've put the generation of these these, from the fibermap, into the mkQSO script. For MEAN_MJD, there is EXP_TIME but not EXP_TIME_EFF, so it is the mean weighted by EXP_TIME, which seemed as good as possible just from the fibermap.

Please have a look at the file /global/cfs/cdirs/desi/survey/catalogs//Y1/QSO/himalayas/QSO_cat_himalayas_main_dark_healpix_only_qso_targets_vtest.fits @julienguy @alxogm 

If all looks good we can tag and make this v1 for himalayas (and it seems unlikely there will be another version given iron should be soon).

**Comment by alxogm** [comment]
Hi @ashleyjross , sorry it took a while to respond. Yes, I think all looks good and you can tag and make the v1 version of the catalogs. Thanks! 

FYI @julienguy I heard from Jiaqi, the DLA finder works well on the catalog.

**Comment by ashleyjross** [comment]
Great, I will just go ahead and change the file names to v1 and then tag the code.

**Comment by ashleyjross** [comment]
I'm re-opening, because when @sbailey had a look he noticed the columns didn't appear to be there (which confuses me, but I'm re-running now) and he also expressed a preference for the following naming convention (which seems reasonable to me):
"I might have a slight preference for COADD_LASTNIGHT etc. to emphasize that this refers to the coadding process (like COADD_FIBERSTATUS and COADD_NUMEXP)"

**Comment by ashleyjross** [comment]
Ok, I figured out why the column names weren't actually appearing and reran, using Stephen's naming suggestion. Code will be tagged and v1 available soon.
